/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trader;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import static jdk.nashorn.internal.objects.NativeString.toLowerCase;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Hell
 */
public class ACustomer extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form users
     */
    public ACustomer() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        conn = db.ConnectDB();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        this.setTitle("Customers");
        Update_table();
        icon();
    }
    
     public void icon(){
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Employee Payroll/Icons/22266-chicken-icon.png")));
    }

    private void Update_table() {
    try{
        String sql ="select id as 'Id',name as 'Name', contact as 'Contact' from customer";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        this.Jtable_allowance.setModel(DbUtils.resultSetToTableModel(rs));
    }   
    catch(SQLException e)
    {
    JOptionPane.showMessageDialog(null, e);
    }finally {
            
            try{
                rs.close();
                pst.close();
                
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_pend = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmd_add1 = new javax.swing.JButton();
        cmd_update = new javax.swing.JButton();
        cmd_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable_allowance = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_id.setEditable(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        txt_username.setNextFocusableComponent(txt_pend);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setText("Id");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel3.setText("Contact");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmd_add1.setText("Add ");
        cmd_add1.setNextFocusableComponent(jButton1);
        cmd_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add1ActionPerformed(evt);
            }
        });
        cmd_add1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmd_add1KeyPressed(evt);
            }
        });

        cmd_update.setText("Edit");
        cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_updateActionPerformed(evt);
            }
        });

        cmd_delete.setText("Delete");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        Jtable_allowance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        Jtable_allowance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtable_allowanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtable_allowance);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(20, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_pend, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(cmd_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmd_update, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmd_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_pend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_add1)
                    .addComponent(cmd_update)
                    .addComponent(cmd_delete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public String capitalizeFirstLetter(String original) {
    if (original == null || original.length() == 0) {
        return original;
    }else{
    return original.substring(0, 1).toUpperCase() + original.substring(1);}
      }
     
    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        // TODO add your handling code here:

        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete record?","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
            String sql ="delete from customer where name=? ";
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_username.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }finally{
            
            try{
                rs.close();
                pst.close();            
            }
            catch(SQLException e)
            {
              JOptionPane.showMessageDialog(null, e);
            }
        }
            

        }
         Update_table();
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_updateActionPerformed
        // TODO add your handling code here:
      try{
      
        String val= String.valueOf(txt_id.getText());
        String val1= String.valueOf(txt_username.getText());
        String val2= String.valueOf(txt_pend.getText());
        
       String sql= "update customer set name='" + val1 + "' ,contact = '"+ val2+"' where Id = '"+ val +"'";
       pst=conn.prepareStatement(sql);
       pst.execute();
       
      JOptionPane.showMessageDialog(this,"Successfully updated","Customer",JOptionPane.INFORMATION_MESSAGE); 
      
        }catch(HeadlessException | SQLException ex){
           JOptionPane.showMessageDialog(this,ex); 
                }finally {
            
            try{
                rs.close();
                pst.close();            
            }
            catch(SQLException e)
            {
              JOptionPane.showMessageDialog(null, e);
            }
        }
       Update_table();
    }//GEN-LAST:event_cmd_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_username.setText("");
       
        txt_pend.setText("");
        txt_id.setText("");
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmd_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add1ActionPerformed
      try{
      // String value1 =  jComboBox1.getSelectedItem().toString();
       String sql= "insert into customer(name,contact)values('"+ txt_username.getText() + "','"+ txt_pend.getText() + "')";
       pst=conn.prepareStatement(sql);
       pst.execute();
     
      JOptionPane.showMessageDialog(this,"Successfully saved","Customer",JOptionPane.INFORMATION_MESSAGE); 
      
      
        }catch(HeadlessException | SQLException ex){
           JOptionPane.showMessageDialog(this,ex); 
                }finally {
            
            try{
                rs.close();
                pst.close();            
            }
            catch(SQLException e)
            {
              JOptionPane.showMessageDialog(null, e);
            }
        }
     
        Update_table();
    }//GEN-LAST:event_cmd_add1ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void Jtable_allowanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtable_allowanceMouseClicked
        // TODO add your handling code here:
        try{
            
            int row= Jtable_allowance.getSelectedRow();
            String table_click= Jtable_allowance.getModel().getValueAt(row, 1).toString();
            String sql= "select * from customer where name= '" + table_click + "'";
             pst=conn.prepareStatement(sql);
             rs=  pst.executeQuery();
            
            if(rs.next()){
                
                String add1=rs.getString("Id");
                txt_id.setText(add1);
                String add2=rs.getString("name");
                txt_username.setText(add2);
                String add3=rs.getString("contact");
                txt_pend.setText(add3);
               
            }
            
            }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }finally {
            
            try{
                rs.close();
                pst.close();            
            }
            catch(SQLException e)
            {
              JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }//GEN-LAST:event_Jtable_allowanceMouseClicked

    private void cmd_add1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmd_add1KeyPressed
       try{
          // String value1 =  jComboBox1.getSelectedItem().toString();
       String sql= "insert into customer(name,contact)values('"+ txt_username.getText() + "','"+ txt_pend.getText() + "')";
       pst=conn.prepareStatement(sql);
       pst.execute();
     
      JOptionPane.showMessageDialog(this,"Successfully saved","Customer",JOptionPane.INFORMATION_MESSAGE); 
       }catch(HeadlessException | SQLException ex){
           JOptionPane.showMessageDialog(this,ex); 
                }finally {
            
            try{
                rs.close();
                pst.close();            
            }
            catch(SQLException e)
            {
              JOptionPane.showMessageDialog(null, e);
            }
        }
     
        Update_table();
    }//GEN-LAST:event_cmd_add1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ACustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ACustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ACustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ACustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ACustomer().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtable_allowance;
    private javax.swing.JButton cmd_add1;
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txt_id;
    public javax.swing.JTextField txt_pend;
    public javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
