/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trader;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.util.Calendar;
import java.util.Locale;
import java.text.DateFormatSymbols;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author Hell
 */
public class AreportNew extends javax.swing.JFrame {
    
    java.util.Date date;
    java.sql.Date sqldate;
    java.sql.Date sqldate1;
    java.sql.Date sqldate4;
    java.text.DateFormatSymbols monthstring;
    Connection conn = null;
    Connection conn1 = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    ResultSet rs1 = null;
    PreparedStatement pst1 = null;
    String yoyo;
    /**
     * Creates new form report
     */
    public AreportNew() {
        initComponents();
    
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        conn = db.ConnectDB();
        conn1 = db.ConnectDB();
        this.setTitle("Customer Report");
        Date date = new Date();
        todays.setDate(date);
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        //lbl_emp.setText(String.valueOf(Emp.empName).toString());
       
        fillcombo1();
        
        icon();
    }
    
    
      private void fillcombo1()
{
     try{
      
      conn=db.ConnectDB();
      String sql= "select name from customer";
      pst=conn.prepareStatement(sql);
      rs=pst.executeQuery();
      while(rs.next()){
          String add=rs.getString("name");
          jComboBox1.addItem(add);
         
         }
        }catch(HeadlessException | SQLException ex){
           JOptionPane.showMessageDialog(this,ex); 
        }finally {
            
            try{
                rs.close();
                pst.close();            
            }
            catch(SQLException e)
            {
              JOptionPane.showMessageDialog(null, e);
            }
        }
}
    
     public void icon(){
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Employee Payroll/Icons/22266-chicken-icon.png")));
    }
     private void sums(){
         int rowCount = jTable1.getRowCount();
        
         int total = 0;
         float total1 = 0;
         int total2 = 0;
         int total3 = 0;
         int total5 = 0;
         try{
    
    for (int i = 0; i < rowCount ; i++){
        total = total + Integer.parseInt(jTable1.getValueAt(i, 1).toString());
        
    }}catch(NumberFormatException e){
                  
            }
         no.setText(String.valueOf(total));
         
         
         ///////////////////////////////////////////////////////////////////
         
        
         
         
         
         
         try{
    
    for (int i = 0; i < rowCount ; i++){
        total2 = total2 + Integer.parseInt(jTable1.getValueAt(i, 2).toString());
        
    }}catch(NumberFormatException e){
                  
            }
         tot.setText(String.valueOf(total2));
         
       //////////////////////////////////////////////////////////////////////////// 
       
     
     }
     
     
 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jProgressBar1 = new javax.swing.JProgressBar();
        Date = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        Date1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_scr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        no = new javax.swing.JTextField();
        tot = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        todays = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("GENERATE REPORT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Date1.setNextFocusableComponent(jButton2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("From:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("To:");

        btn_scr.setText("Search");
        btn_scr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scrActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Calculate");
        jButton2.setNextFocusableComponent(jButton1);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Quantity");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Total Amount");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Date :");

        jLabel11.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel11.setText("Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_scr))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel6)
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))))
                                .addGap(94, 94, 94)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(todays, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_scr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Date1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addComponent(todays, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
        date = todays.getDate();
        sqldate4 = new java.sql.Date(date.getTime());
            String sqldate8 = String.valueOf(sqldate4);
          String userhome = System.getProperty("user.home");
          JFileChooser dialog = new JFileChooser(userhome +"\\Desktop");
            dialog.setSelectedFile(new File(" "+ sqldate8 + " Report.pdf"));
            int dialogResult = dialog.showSaveDialog(null);
            if (dialogResult==JFileChooser.APPROVE_OPTION){
            String filePath = dialog.getSelectedFile().getPath();
           
            
        try {
            
            date = Date.getDate();
            sqldate = new java.sql.Date(date.getTime());
            String sqldate2 = String.valueOf(sqldate);
            
            date = Date1.getDate();
            sqldate1 = new java.sql.Date(date.getTime());
            String sqldate3 = String.valueOf(sqldate1);
            
            date = todays.getDate();
            sqldate4 = new java.sql.Date(date.getTime());
            String sqldate5 = String.valueOf(sqldate4);
            SimpleDateFormat f = new SimpleDateFormat("MMMMMMMMM");
            SimpleDateFormat f1 = new SimpleDateFormat("YYYY");
             String mont = f.format(new Date());
             String yea = f1.format(new Date());
            
             
              int mac4 = Integer.parseInt(no.getText());
             String max4= Integer.toString(mac4);
             int mac5 = Integer.parseInt(tot.getText());
             String max5= Integer.toString(mac5);
             String value1 =  jComboBox1.getSelectedItem().toString();
             
     
             String sql ="select * from Retail where date BETWEEN '"+sqldate2+"' and '"+sqldate3+"' AND cust_name='"+value1+"' ";
             pst=conn.prepareStatement(sql);
             rs=pst.executeQuery();
             
           

           Document myDocument = new Document();
           PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath ));
           PdfPTable table = new PdfPTable(6);
           
           myDocument.open();
           
           float[] rowHeights = new float[] {6,6,6,6,6,6};
           table.setWidths(rowHeights);
           table.setWidthPercentage(100); //set table width to 100%
          // table.setHorizontalAlignment(Element.ALIGN_LEFT);
          myDocument.add(new Paragraph("                                                                                                                                                                              ", FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD)));
          myDocument.add(new Paragraph("                                                                                                                                                                ", FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD)));  
          myDocument.add(new Paragraph("               Point Of Sale & Inventory Management",FontFactory.getFont(FontFactory.TIMES_BOLD,22,Font.BOLD )));
          myDocument.add(new Paragraph(" Monthly Report : "+value1,FontFactory.getFont(FontFactory.TIMES_BOLD,15,Font.BOLD)));
          
           myDocument.add(new Paragraph("                                                                                                                                                              Date : "+sqldate5,FontFactory.getFont(FontFactory.TIMES_BOLD,11,Font.PLAIN )));
          myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
          //myDocument.add(new Paragraph(new Date().toString()));
          myDocument.add(new Paragraph("           "));
         
          
          table.addCell(new PdfPCell(new Paragraph("ID",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("DATE",FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("ITEMS",FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("QUANTITY",FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("RATE",FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("AMOUNT",FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.BOLD))));
          
           
         
           
          while(rs.next())
            {
           table.addCell(new PdfPCell(new Paragraph(rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(5),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(6),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(7),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           
           
            } 
          
          table.addCell(new PdfPCell(new Paragraph("TOTAL",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph(""+max4,FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph(""+max5,FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
          
          
          //MessageFormat header = new MessageFormat("INVOICE");
          //MessageFormat footer = new MessageFormat("page");
          //try{
          //jTable1.print(JTable.PrintMode.FIT_WIDTH,header, footer );
          //}catch(Exception e){
          //JOptionPane.showMessageDialog(null,"Unable to print");
          //}
          
           myDocument.add(table);
           //myDocument.add(new Paragraph("TOTAL                         "+max+"                                 "+""+max1+"                                                                                 "+ max2 + "                       " + max3,FontFactory.getFont(FontFactory.TIMES_BOLD,9,Font.PLAIN )));
          
           myDocument.add(new Paragraph("                                                                                                                                                                                   Powered By : Trask Services ",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD )));
            myDocument.close();
             
           JOptionPane.showMessageDialog(null,"Report successfully generated");
           
     }
        catch(DocumentException | HeadlessException | FileNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e); 
        }
        
      finally {
            try{
                rs.close();
                pst.close();
            }
            catch(SQLException e)
            {
              JOptionPane.showMessageDialog(null,e); 
            }
        }
        
        ///////////////////////////////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////////////////////////////////////////////////////
        
        
        
        
      }     
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_scrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scrActionPerformed
        // TODO add your handling code here:
         try{
             //String input_emp = txt_search.getText();
            //int input_emp_id = Integer.parseInt(input_emp);
             date = Date.getDate();
            sqldate = new java.sql.Date(date.getTime());
             date = Date.getDate();
            sqldate = new java.sql.Date(date.getTime());
            String sqldate2 = String.valueOf(sqldate);
            
            date = Date1.getDate();
            sqldate1 = new java.sql.Date(date.getTime());
            String sqldate3 = String.valueOf(sqldate1);
            //String[] splitDate = sqldate2.split("-");
            //int retMonth = date.getMonth() + 1;
            //int retYear = date.getYear() + 1900;
             //int retYear2 = date.getYear();
             SimpleDateFormat f = new SimpleDateFormat("MMMMMMMMM");
             SimpleDateFormat f1 = new SimpleDateFormat("YYYY");
             String mont = f.format(new Date());
             String yea = f1.format(new Date());
            String value1 =  jComboBox1.getSelectedItem().toString();
            
            String sql ="select date as 'DATE',qua as 'QUANTITY',total as 'TOTAL' FROM Retail where date BETWEEN '"+sqldate2+"' and '"+sqldate3+"' AND cust_name='"+value1+"' ";
            pst=conn.prepareStatement(sql);
            //pst.setDate(1,getCurrentDate());
           
           
            
            rs=pst.executeQuery();
            this.jTable1.setModel(DbUtils.resultSetToTableModel(rs));
         
            }catch(NumberFormatException | SQLException e)
        {
            //JOptionPane.showMessageDialog(null, e);
        }finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(null, "No Record Found");
            }
        }
        
        ////////////////////////////////////////////////////////////////////////////////////////////////////////
        
        
       
        
    }//GEN-LAST:event_btn_scrActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       sums();
       
           
              
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreportNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreportNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreportNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreportNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreportNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date;
    private com.toedter.calendar.JDateChooser Date1;
    private javax.swing.JButton btn_scr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField no;
    private com.toedter.calendar.JDateChooser todays;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables
}
